[package]
name = "altersend_storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
altersend_mux = { path = "../altersend_mux" }
blake2 = "0.10"
compact-encoding = "2.2"
hex = { workspace = true }
hypercore_schema = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dependencies.hypercore]
version = "0.16"
default-features = false
features = ["tokio", "replication"]

[dependencies.hypercore-protocol]
version = "0.7"
default-features = true
