// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`

Future<void> initEngine({required String storagePath}) =>
    AlterSendBridge.instance.api.crateApiInitEngine(storagePath: storagePath);

/// JSON-encoded [`altersend_domain::TransferUiSnapshot`].
Future<String> getUiSnapshotJson() =>
    AlterSendBridge.instance.api.crateApiGetUiSnapshotJson();

Future<void> addSelectedFiles({
  required List<String> paths,
  required List<String> names,
  required Uint64List sizes,
}) => AlterSendBridge.instance.api.crateApiAddSelectedFiles(
  paths: paths,
  names: names,
  sizes: sizes,
);

Future<void> continueShare() =>
    AlterSendBridge.instance.api.crateApiContinueShare();

Future<void> joinSession({required String joinCode}) =>
    AlterSendBridge.instance.api.crateApiJoinSession(joinCode: joinCode);

Future<void> downloadAllFiles() =>
    AlterSendBridge.instance.api.crateApiDownloadAllFiles();

Future<void> clearSession() =>
    AlterSendBridge.instance.api.crateApiClearSession();

Future<bool> isValidJoinCode({required String code}) =>
    AlterSendBridge.instance.api.crateApiIsValidJoinCode(code: code);

Future<String?> extractJoinCode({required String text}) =>
    AlterSendBridge.instance.api.crateApiExtractJoinCode(text: text);
